# Generated by Django 3.2.9 on 2022-03-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('MyApp', '0002_auto_20220316_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
