# Generated by Django 3.2.9 on 2022-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_delete_personne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('heure', models.DateTimeField()),
            ],
        ),
    ]
