# Generated by Django 3.2.12 on 2022-03-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_interschool', '0002_auto_20220309_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Evenement',
        ),
    ]
